services:
  redis:
    image : "redis:alpine"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data 
  
  fastapi-app:
    build: . 
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app
    depends_on:
      - redis

volumes:
  redis_data: